* QUESTION NO 0]         

* Write down 3-5 methods applicable to each data type. (Hint: extend, reverse, etc.




In [ ]:
list1= [1, 2, 3]
print("The list is:",list1)
list1.append(4)
print("After append the list is:\n",list1)
list1.extend([5, 6])
print("After extend the list is:\n",list1)
list1.reverse()
print("After reverse the list is:\n",list1)
list1.sort()
print("After sorting the list is:\n",list1)
list1.pop()
print("After using pop the list is:\n",list1)

string1= "Hello, World!"
print("The string is:\n",string1)
upper_string=string1.upper()
print("The upper string is:\n",upper_string)
lower_string=string1.lower()
print("The lower string is:\n",lower_string)
stripped_string=string1.strip()
print("The stripped string is:\n",stripped_string)
new_string=string1.replace("Hello", "Hi")
print("The new string is:\n",new_string)
substring_list=string1.split(", ")
print("The sub string is:\n",substring_list)


my_dict= {"name": "aisha", "age": 30}
print(my_dict)
keys_list= list(my_dict.keys())
print("The keys of dictionary are:\n",keys_list)
values_list= list(my_dict.values())
print("The values of dictionary are:\n",values_list)
items_list = list(my_dict.items())
print("The items of dictionary are:\n",items_list)
age = my_dict.get("age", 0)
print("The change in age of dictionary is:\n",age)
my_dict.update({"city": "New York"})
print("The updated dictionary is:\n",my_dict)


tuple1=('student', 56, (8,4),[6,'teachers'])
tuple2 =(3, 4)
print(tuple1)
print(tuple2)
concatenated_tuple= tuple1 + tuple2
print("The concatenated tupl is",concatenated_tuple)
length = len(tuple1)
print("The length of tuple is:",length)



set1={88,56,23,5,'board'}
print(set1)
set1.add(6)
print(set1)
set1.remove(23)
print(set1)
set1.discard(5)
print(set1)



The list is: [1, 2, 3]
After append the list is:
 [1, 2, 3, 4]
After extend the list is:
 [1, 2, 3, 4, 5, 6]
After reverse the list is:
 [6, 5, 4, 3, 2, 1]
After sorting the list is:
 [1, 2, 3, 4, 5, 6]
After using pop the list is:
 [1, 2, 3, 4, 5]
The string is:
 Hello, World!
The upper string is:
 HELLO, WORLD!
The lower string is:
 hello, world!
The stripped string is:
 Hello, World!
The new string is:
 Hi, World!
The sub string is:
 ['Hello', 'World!']
{'name': 'aisha', 'age': 30}
The keys of dictionary are:
 ['name', 'age']
The values of dictionary are:
 ['aisha', 30]
The items of dictionary are:
 [('name', 'aisha'), ('age', 30)]
The change in age of dictionary is:
 30
The updated dictionary is:
 {'name': 'aisha', 'age': 30, 'city': 'New York'}
('student', 56, (8, 4), [6, 'teachers'])
(3, 4)
The concatenated tupl is ('student', 56, (8, 4), [6, 'teachers'], 3, 4)
The length of tuple is: 4
{56, 5, 23, 88, 'board'}
{56, 5, 6, 23, 88, 'board'}
{56, 5, 6, 88, 'board'}
{56, 6, 88, 'boar

*   QUESTION NO 1]
*  Define a function, which takes in two strings A and B. Reverses the first string A, adds it to B, and returns the final string.

In [ ]:
def reverse_and_concatenate(A, B):
    reversed_A = A[::-1]
    result = reversed_A + B
    return result

string_A = "Hello"
string_B = " World"
final_string = reverse_and_concatenate(string_A, string_B)
print(final_string)

olleH World




*   QUESTION NO 2]
*   Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.
work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
Answer : the female worker that worked the most hours is Penny and she should be paid 18400



In [ ]:
def find_female_worker_with_most_hours(work_hours):
    max_hours = 0
    female_worker = None
    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_worker = name
    if female_worker:
        pay = max_hours * 20
        return f"The female worker that worked the most hours is {female_worker} and she should be paid ${pay}"
    else:
        return "No female workers found in the list."

work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'), ('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]
result = find_female_worker_with_most_hours(work_hours)
print(result)

The female worker that worked the most hours is Penny and she should be paid $18400




*   QUESTION NO. 3]-a)
*   a)Create a 5x5 matrix of the following form,
[[1,1]
[2,2]]
i.e. each row is increasing and has repetive elements.
Hint : you can use hstack, vstack etc.



In [ ]:
import numpy as np

small_matrix = np.array([[1, 1], [2, 2]])

matrix = np.tile(small_matrix, (2, 2))

print(matrix)

[[1 1 1 1]
 [2 2 2 2]
 [1 1 1 1]
 [2 2 2 2]]




*   QUESTION NO 3]-b)
*   b) Find dot product of the matrix with any matrix. (Figure out the size/ shape of the matrix)



In [ ]:
import numpy as np

matrix1 = np.array([[6, 7], [7, 9]])
matrix2 = np.array([[3, 6], [2, 1]])

if matrix1.shape[1] == matrix2.shape[0]:
    dot_product = np.dot(matrix1, matrix2)
    print("Dot Product:")
    print(dot_product)
else:
    print("Matrix dimensions are not compatible for dot product.")

Dot Product:
[[32 43]
 [39 51]]




*   QUESTION NO. 3]
*   Upload an image to your google drive, Use plt.imread to read image from the google drive and then print that image using plt.imshow



In [ ]:
from google.colab import drive
drive.mount('/content/drive/MyDrive/BTS/a8b8ae8b8c5a147c6bc4bfdb641db560.jpg')
image_path = '/content/drive/MyDrive/BTS/a8b8ae8b8c5a147c6bc4bfdb641db560.jpg'

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

image = mpimg.imread(image_path)

plt.imshow(image)
plt.axis('off')
plt.show()


ValueError: ignored